#
#  Logging - Konfigurationsfile f. Logging in PictureDatabase
#  November 2021 - RZ
#
# Genutzt wird java.util.logging
# Einlesen der Konfiguration ueber den LogManager.
#
# Logging zumnaechst auf die Konsole.
#
#    *********************************************
#    *  Dies File wird nicht gelesen             *
#    *  Das Produktionsfile is in home/.imageDB  *
#    *********************************************
#
handlers= java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.ConsoleHandler.level = FINER

#
# Default Log Level, falls nicht anders angegeben
.level=SEVERE
initial.level=SEVERE
picdata.level=SEVERE
pictures.level=SEVERE
pictures.PicturesDatabase.level=SEVERE
pictures.tools.PresentationPicturesProzessor.level=SEVERE
pictures.tools.MediumLoadProcessor.level=SEVERE
pictures.ui.ToolsUI.level=SEVERE
pictures.ui.MaintainPictureMediumUI.level=SEVERE
pictures.tools.PresentationPicturesProcessor.level=SEVERE


