 use PIC_DEV;
 SET FOREIGN_KEY_CHECKS=0;
 DELETE FROM DIGI_PICTURE;
 DELETE FROM CAMERA;
 DELETE FROM PICTURE_MEDIUM;
 DELETE FROM PIC_DIRECTORY;
 DELETE FROM PIC_DIR_MAP;
 # DELETE FROM MEDIUM_TYPE;
 SET FOREIGN_KEY_CHECKS=1;
 
 TRUNCATE TABLE DIGI_PICTURE;
 TRUNCATE TABLE CAMERA;
 TRUNCATE TABLE PICTURE_MEDIUM;
 TRUNCATE TABLE PIC_DIRECTORY;
 TRUNCATE TABLE PIC_DIR_MAP;
 # TRUNCATE TABLE MEDIUM_TYPE;
 
